channels:
  - rosettacommons
  - bioconda
  - r
  - conda-forge
  - defaults
  - schrodinger
dependencies:
  - attrs=19.1.0
  - backcall=0.1.0
  - bleach=3.1.0
  - blosc=1.16.3
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.5.0
  - descartes=1.1.0
  - entrypoints=0.3
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - glib=2.58.3
  - gst-plugins-base=1.14.4
  - gstreamer=1.14.4
  - icu=58.2
  - ipykernel=5.1.1
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9c
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - matplotlib-base=3.1.0
  - mistune=0.8.4
  - mizani=0.5.4
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.8
  - numpy=1.16.4
  - openblas=0.3.5
  - openssl=1.1.1b
  - palettable=3.1.1
  - pandas=0.24.2
  - pandoc=2.7.2
  - pandocfilters=1.4.2
  - parso=0.4.0
  - patsy=0.5.1
  - pcre=8.41
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.1.1
  - plotnine=0.5.1
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pygments=2.4.2
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrosetta=2018.51+HEAD.bae0185c8be
  - pyrsistent=0.15.2
  - python=3.7.3
  - python-blosc=1.8.1
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyzmq=18.0.1
  - qt=5.9.7
  - qtconsole=4.5.1
  - readline=7.0
  - scipy=1.3.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - statsmodels=0.9.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - tornado=6.0.2
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - widgetsnbextension=3.4.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11

